### ISSUE TITLE
rename this to "yat" (Yet Another Tokeniser)

### ISSUE THREAD

**Issue by pro465** [jsdw/yap#1]
the examples seems to suggest that this is actually a tokeniser, not a parser. i might be wrong tho, in which case you can close this issue.

**Comment by jsdw** [comment]
I don't think that's true; `json_logos` uses logos to tokenize and yap to parse the tokens into a Json representation, and `json` skips tokenizing and goes straight from input string to Json representation, which is pretty much how most parser combinator libraries expect to be used :)

**Comment by pro465** [comment]
@jsdw 
> ...`json` skips tokenizing and goes straight from input string to Json representation,  ...

well, i could theoretically just skip everything and directly compile to machine code using `yap`, but that would not make `yap` a compiler, would it?

**Comment by jsdw** [comment]
At the end of the day, I feel like the aims/usage of this library are most similar to libraries that tend to be called parsing libraries or parser combinator libraries, so the current name is the best fit. 

That said, you could pick any "parser combinator" or "parser" library and use it for tokenizing the input as well, so there is plenty of overlap, and IMO the naming should just reflect the overlap with similar libraries and expected usage :)
