### ISSUE TITLE
Consider using rustfmt and checking that in CI

### ISSUE THREAD

**Issue by jcgruenhage** [jsdw/yap#4]
While reviewing `yap` (see review [here](https://git.jcg.re/jcgruenhage/crev-proofs/commit/ee6ef0f2968ea678dfc14c24a3f2c1b32ea14ec3)), I noticed that yap does have some spaces in places where I wouldn't expect them. After running `cargo fmt`, I found that there's nearly 300 lines that rustfmt would change. Because that's not really an original contribution, I won't be opening a PR, just want to get some feedback on this in issue form.

**Comment by jcgruenhage** [comment]
If you're not opposed to this in general, I can also take care of opening a PR that both adds the changes done by rustfmt and add a pipeline check for it. And thanks for your work on yap, and for merging my PRs!

**Comment by jsdw** [comment]
I'd love that; it'd be very much appreciated :)
